alias py='python3'
alias update='sudo apt update && apt list --upgradeable'
alias upgrade='sudo apt upgrade'
alias upgradeable='apt list --upgradable'
alias clip='xsel -ib'
alias sensors='sensors -f'
alias m='make'
alias mr='make run'
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
